str="prahalad is a good boy"

"""
print(str)
print(len(str))
print(str[5])
print(str[0:10])
print(str[0:10:2])
print(str[0:])
print(str[:20])
print(str[:])
print(str[::])
print(str[::-1])
print(str[::2])
print(str[-5:-2])
print(str[-5::-2])
print(str.isalnum())
print(str.isalpha())
print(str.endswith("boy"))
print(str.endswith("bdoy"))
print(str.count("o"))
print(str.capitalize())
print(str.lower())
print(str.upper())
print(str.replace("is","are"))
"""